version: '3.4'

services:
  reverse-proxy:
    image: nginx:1.17
    volumes:
      - ./nginx/default.dev.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    networks:
      - techaround
  db:
    image: postgres
    environment:
      - POSTGRES_USER=techaround
      - POSTGRES_DB=techaround
      - POSTGRES_PASSWORD=techaround
    ports:
      - 5433:5432
    networks:
      - techaround
  api:
    build:
      context: ./api/
      dockerfile: ./Dockerfile
    container_name: techaround-api
    hostname: techaround-api
    env_file:
      - ./.dev.env
    volumes:
      - ./api/.:/app
    working_dir: /app
    command: bash -c "cargo watch -x run"
    ports:
      - "3000:3000"
    depends_on: 
      - db
    networks:
      - techaround
  front:
    build: 
      context: ./front/
      dockerfile: ./Dockerfile
    container_name: techaround-front
    hostname: techaround-front
    env_file:
      - ./.dev.env
    volumes:
      - ./front/.:/app
    working_dir: /app
    command: bash -c "trunk serve"
    ports: 
      - "8080:8080"
    depends_on: 
      - api
    networks:
      - techaround
networks:
  techaround:
