[package]
name = "techaround-front"
version = "0.1.0"
authors = ["Cyril Couffe <c.couffe@datailor.fr>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
yew = "0.19.3"